"""initial_schema

Revision ID: 4075fc028452
Revises:
Create Date: 2026-06-07 20:06:10.832012

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4075fc028452"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "preferences",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("user_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("pace", sa.String(length=20), nullable=True),
        sa.Column("luxury_tier", sa.String(length=20), nullable=True),
        sa.Column("walking_tolerance", sa.String(length=20), nullable=True),
        sa.Column("food_prefs", sa.JSON(), nullable=True),
        sa.Column("interests", sa.JSON(), nullable=True),
        sa.Column("budget_behavior", sa.String(length=20), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "trips",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("user_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("destination_city", sa.String(length=255), nullable=False),
        sa.Column("destination_country", sa.String(length=2), nullable=True),
        sa.Column("latitude", sa.Double(), nullable=True),
        sa.Column("longitude", sa.Double(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("num_travelers", sa.Integer(), nullable=False),
        sa.Column("budget_total", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("budget_currency", sa.String(length=3), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("end_date >= start_date", name="chk_trip_dates"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_trips_status", "trips", ["status"], unique=False)
    op.create_index("idx_trips_user_id", "trips", ["user_id"], unique=False)
    op.create_table(
        "approvals",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("trip_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("proposed_by", sa.String(length=50), nullable=False),
        sa.Column("change_type", sa.String(length=50), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["trip_id"], ["trips.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_approvals_trip_status", "approvals", ["trip_id", "status"], unique=False)
    op.create_table(
        "budget_logs",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("trip_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("category", sa.String(length=20), nullable=False),
        sa.Column("planned_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("actual_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "logged_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["trip_id"], ["trips.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_budget_logs_trip_id", "budget_logs", ["trip_id"], unique=False)
    op.create_table(
        "event_logs",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("trip_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("user_id", sa.UUID(as_uuid=False), nullable=True),
        sa.Column("actor", sa.String(length=50), nullable=False),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("detail", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["trip_id"], ["trips.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_event_logs_created_at", "event_logs", ["created_at"], unique=False)
    op.create_index("idx_event_logs_trip_id", "event_logs", ["trip_id"], unique=False)
    op.create_table(
        "hotel_candidates",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("trip_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("provider", sa.String(length=20), nullable=False),
        sa.Column("provider_hotel_id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("star_rating", sa.Numeric(precision=2, scale=1), nullable=True),
        sa.Column("latitude", sa.Double(), nullable=True),
        sa.Column("longitude", sa.Double(), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("image_url", sa.Text(), nullable=True),
        sa.Column("price_total", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("price_currency", sa.String(length=3), nullable=True),
        sa.Column("price_per_night", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("meal_plan", sa.String(length=20), nullable=True),
        sa.Column("refundable", sa.Boolean(), nullable=True),
        sa.Column("booking_ref", sa.String(length=255), nullable=True),
        sa.Column("match_score", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("is_selected", sa.Boolean(), nullable=False),
        sa.Column("raw_payload", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["trip_id"], ["trips.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_hotel_candidates_trip_id", "hotel_candidates", ["trip_id"], unique=False)
    op.create_table(
        "itinerary_items",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("trip_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("day_number", sa.Integer(), nullable=False),
        sa.Column("item_date", sa.Date(), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=True),
        sa.Column("end_time", sa.Time(), nullable=True),
        sa.Column("item_type", sa.String(length=20), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("latitude", sa.Double(), nullable=True),
        sa.Column("longitude", sa.Double(), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("source_provider", sa.String(length=50), nullable=True),
        sa.Column("source_ref", sa.String(length=255), nullable=True),
        sa.Column("est_cost", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("est_cost_currency", sa.String(length=3), nullable=True),
        sa.Column("is_outdoor", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["trip_id"], ["trips.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_itinerary_items_trip_day", "itinerary_items", ["trip_id", "day_number"], unique=False
    )
    op.create_table(
        "traveler_profiles",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("trip_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("is_lead", sa.Boolean(), nullable=False),
        sa.Column("age_band", sa.String(length=20), nullable=True),
        sa.Column("prefs_override", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["trip_id"], ["trips.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_traveler_profiles_trip_id", "traveler_profiles", ["trip_id"], unique=False)
    op.create_table(
        "weather_snapshots",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("trip_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("snapshot_date", sa.Date(), nullable=False),
        sa.Column("temp_min_c", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("temp_max_c", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("precipitation_mm", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("condition_code", sa.Integer(), nullable=True),
        sa.Column("is_adverse", sa.Boolean(), nullable=False),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["trip_id"], ["trips.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_weather_trip_date", "weather_snapshots", ["trip_id", "snapshot_date"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_weather_trip_date", table_name="weather_snapshots")
    op.drop_table("weather_snapshots")
    op.drop_index("idx_traveler_profiles_trip_id", table_name="traveler_profiles")
    op.drop_table("traveler_profiles")
    op.drop_index("idx_itinerary_items_trip_day", table_name="itinerary_items")
    op.drop_table("itinerary_items")
    op.drop_index("idx_hotel_candidates_trip_id", table_name="hotel_candidates")
    op.drop_table("hotel_candidates")
    op.drop_index("idx_event_logs_trip_id", table_name="event_logs")
    op.drop_index("idx_event_logs_created_at", table_name="event_logs")
    op.drop_table("event_logs")
    op.drop_index("idx_budget_logs_trip_id", table_name="budget_logs")
    op.drop_table("budget_logs")
    op.drop_index("idx_approvals_trip_status", table_name="approvals")
    op.drop_table("approvals")
    op.drop_index("idx_trips_user_id", table_name="trips")
    op.drop_index("idx_trips_status", table_name="trips")
    op.drop_table("trips")
    op.drop_table("preferences")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
