"""add_share_token_to_trips

Revision ID: 545e5bb6b304
Revises: b1df5cfd3ec3
Create Date: 2026-06-20 00:03:47.316590

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "545e5bb6b304"
down_revision: str | Sequence[str] | None = "b1df5cfd3ec3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("trips", sa.Column("share_token", sa.String(length=36), nullable=True))
    op.add_column("trips", sa.Column("share_expires_at", sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f("ix_trips_share_token"), "trips", ["share_token"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_trips_share_token"), table_name="trips")
    op.drop_column("trips", "share_expires_at")
    op.drop_column("trips", "share_token")
    # ### end Alembic commands ###
