"""add_user_feedback_table

Revision ID: 5845b0bf9c6e
Revises: a38630cc2264
Create Date: 2026-06-18 23:26:55.437501

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5845b0bf9c6e"
down_revision: str | Sequence[str] | None = "a38630cc2264"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_feedback",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("user_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("trip_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("approval_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("change_type", sa.String(length=64), nullable=False),
        sa.Column("decision", sa.String(length=16), nullable=False),
        sa.Column("context_tags", sa.JSON(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["approval_id"], ["approvals.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["trip_id"], ["trips.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_user_feedback_created_at", "user_feedback", ["created_at"], unique=False)
    op.create_index("idx_user_feedback_user_id", "user_feedback", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_user_feedback_user_id", table_name="user_feedback")
    op.drop_index("idx_user_feedback_created_at", table_name="user_feedback")
    op.drop_table("user_feedback")
    # ### end Alembic commands ###
