"""add_conflict_warning_to_itinerary_items

Revision ID: a38630cc2264
Revises: d5a69b21efbb
Create Date: 2026-06-18 20:37:16.221318

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a38630cc2264"
down_revision: str | Sequence[str] | None = "d5a69b21efbb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("itinerary_items", sa.Column("conflict_warning", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("itinerary_items", "conflict_warning")
    # ### end Alembic commands ###
