"""add_packing_list_to_trips

Revision ID: b1df5cfd3ec3
Revises: 5845b0bf9c6e
Create Date: 2026-06-19 20:37:41.428909

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b1df5cfd3ec3"
down_revision: str | Sequence[str] | None = "5845b0bf9c6e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("trips", sa.Column("packing_list", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("trips", "packing_list")
    # ### end Alembic commands ###
