"""widen_destination_country_to_100

Revision ID: d5a69b21efbb
Revises: b2c3d4e5f6a7
Create Date: 2026-06-13 02:31:21.343646

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d5a69b21efbb"
down_revision: str | Sequence[str] | None = "b2c3d4e5f6a7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "trips",
        "destination_country",
        existing_type=sa.VARCHAR(length=2),
        type_=sa.String(length=100),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "trips",
        "destination_country",
        existing_type=sa.String(length=100),
        type_=sa.VARCHAR(length=2),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
