"""add_cover_image_url_to_trips

Revision ID: f3f5215ec0b8
Revises: 545e5bb6b304
Create Date: 2026-06-20 00:55:35.173570

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f3f5215ec0b8"
down_revision: str | Sequence[str] | None = "545e5bb6b304"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("trips", sa.Column("cover_image_url", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("trips", "cover_image_url")
    # ### end Alembic commands ###
